version: "3.9"

services:
    db:
        container_name: flyway-demo-database
        image: mcr.microsoft.com/mssql/server:2019-latest
        environment:
            - MSSQL_SA_PASSWORD=Password123!
            - ACCEPT_EULA=Y
        ports:
            - "1433:1433"

    sqlcmd:
        container_name: sqlcmd
        image: mcr.microsoft.com/mssql-tools:latest
        command: /opt/startup-scripts/run-initialization.sh
        stdin_open: true
        volumes:
            - ./startup-scripts:/opt/startup-scripts
        depends_on:
            - db
        restart: on-failure

    flyway:
        container_name: flyway
        image: "flyway/flyway:9.22-alpine"
        command: -url='jdbc:sqlserver://db:1433;encrypt=true;trustServerCertificate=true;databaseName=DemoDB' -user=sa -password=Password123! -connectRetries=60 migrate
        volumes:
            - ./sql/:/flyway/sql
        depends_on:
            - sqlcmd
